# \u7AEF\u53E3\u53F7
server:
  port: 30041
# \u670D\u52A1\u540D\u79F0
spring:
  application:
    name: hystrix-failback
    # 需要bean重载
  main:
    allow-bean-definition-overriding: true
# eureka server \u914D\u7F6E\uFF08\u5355\u670D\u52A1\u914D\u7F6E\uFF09
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30001/eureka/
# actuator \u66B4\u9732\u5168\u90E8\u7AEF\u53E3 \uFF08\u5F00\u53D1\u65F6\u914D\u7F6E\uFF09
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
# ribbon 单服务配置负载均衡策略
#ribbon-server:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.tkn.ribbonclient.rules.Myrule

# 开启Feign下面的Hystrix功能
feign:
  hystrix:
    enabled: true
## 是否开启服务降级
#hystrix:
#  command.default.fallback.enabled: true
## 全局超时
#  command.default.execution.timeout.enabled: true
## 超时时间
#  command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
## 超时以后终止线程
#  command.default.execution.isolation.thread.interruptOnTimeout: true
## 取消的时候终止线程
#  command.default.execution.isolation.thread.interruptOnFutureCancel: true
## hystrix.command.MyService#retry(int).execution.isolation.thread.timeoutInMilliseconds=3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 取消的时候终止线程
            interruptOnFutureCancel: true
            # 超时以后终止线程
            interruptOnTimeout: true
            # 超时时间
            timeoutInMilliseconds: 1000
        timeout:
          # 全局超时
          enabled: true
      fallback:
        # 是否开启服务降级
        enabled: true
      circuitBreaker:
        # 开启熔断器功能
        enabled: true
        # 超过50%的失败请求，则熔断开关开启
        errorThresholdPercentage: 50
        # 强制关闭熔断开关
        forceClosed: false
        # 强制开启熔断开关
        forceOpen: false
        # 熔断的前提条件（请求的数量），在一定的时间窗口内，请求达到5个以后，才开始进行熔断判断
        requestVolumeThreshold: 5
        # 当熔断开启以后，经过多少秒再进入半开状态
        sleepWindowInMilliseconds: 15000
      metrics:
        rollingStats:
          # 配置时间窗口
          timeInMilliseconds: 20000
feign-server:
  ribbon:
    # 连接超时
    ConnectTimeout: 4000
    # 每台机器最大重试次数
    MaxAutoRetries: 0
    # 可以再重试几台机器
    MaxAutoRetriesNextServer: 0
    # 在所有HTTP Method进行重试
    OkToRetryOnAllOperations: false
    # 业务处理超时
    ReadTimeout: 8000
